### ISSUE TITLE
irods-catalog-provider post install test failure

### ISSUE THREAD

**Issue by MartinSchobben** [irods/irods_demo#55]
When standing up the `irods-catalog-provider` I get the following error:

```
irods_demo-irods-catalog-provider-1  | Error encountered running setup_irods:
irods_demo-irods-catalog-provider-1  | Traceback (most recent call last):
irods_demo-irods-catalog-provider-1  |   File "/var/lib/irods/scripts/setup_irods.py", line 523, in main
irods_demo-irods-catalog-provider-1  |     setup_server(irods_config,
irods_demo-irods-catalog-provider-1  |   File "/var/lib/irods/scripts/setup_irods.py", line 148, in setup_server
irods_demo-irods-catalog-provider-1  |     test_put(irods_config)
irods_demo-irods-catalog-provider-1  |   File "/var/lib/irods/scripts/setup_irods.py", line 180, in test_put
irods_demo-irods-catalog-provider-1  |     raise IrodsError('Post-install test failed. Please check your configuration.')
irods_demo-irods-catalog-provider-1  | irods.exceptions.IrodsError: Post-install test failed. Please check your configuration.
```

**Comment by trel** [comment]
Hmm.

Remember that the hostname will change on each launch... and that matters.

So you have to clear the existing image...

```
$ docker compose down && docker compose up irods-catalog-provider
```

**Comment by MartinSchobben** [comment]
oh yes, I see. closing
